#!/usr/bin/env bash
# btrfs-subvols.sh – Create Btrfs subvolumes and migrate the installed system.
#
# Runs INSIDE the target chroot (invoked by setup.sh via `chroot /target`).
# At this point `/` inside the chroot is the Btrfs top-level subvolume
# (subvolid=5) as mounted by the Debian installer.
#
# Subvolume layout created:
#   @           → /
#   @home       → /home
#   @snapshots  → /.snapshots
#   @var_log    → /var/log
#
# After this script completes, setup.sh unmounts the top-level Btrfs,
# remounts using the above subvolumes, and continues.

set -euo pipefail

BTRFS_TOPVOL=/mnt/btrfs-top
BTRFS_OPTS="${BTRFS_OPTS:-defaults,compress=zstd:3,noatime,space_cache=v2}"

log()  { echo "[btrfs-subvols] $*"; }
die()  { log "ERROR: $*"; exit 1; }

# ---------------------------------------------------------------------------
# 1. Detect the root Btrfs block device
# ---------------------------------------------------------------------------

ROOT_DEV="$(findmnt -n -o SOURCE / 2>/dev/null)" \
    || die "Cannot determine root block device"
log "Root Btrfs device: ${ROOT_DEV}"

# Strip any leading subvol path that findmnt may append (e.g. /dev/sda3[/@])
ROOT_DEV="${ROOT_DEV%%\[*\]}"
log "Resolved block device: ${ROOT_DEV}"

# ---------------------------------------------------------------------------
# 2. Mount the Btrfs top-level subvolume (subvolid=5)
# ---------------------------------------------------------------------------

mkdir -p "${BTRFS_TOPVOL}"
mount -t btrfs -o subvolid=5 "${ROOT_DEV}" "${BTRFS_TOPVOL}" \
    || die "Cannot mount top-level Btrfs subvolume"

# ---------------------------------------------------------------------------
# 3. Create subvolumes
# ---------------------------------------------------------------------------

for sv in @ @home @snapshots @var_log; do
    if btrfs subvolume show "${BTRFS_TOPVOL}/${sv}" &>/dev/null; then
        log "Subvolume ${sv} already exists – skipping creation"
    else
        btrfs subvolume create "${BTRFS_TOPVOL}/${sv}"
        log "Created subvolume: ${sv}"
    fi
done

# ---------------------------------------------------------------------------
# 4. Populate @ with the current root tree (excluding subvolume mountpoints)
# ---------------------------------------------------------------------------

log "Syncing root filesystem into @..."
rsync -axHAX \
    --exclude=/proc \
    --exclude=/sys \
    --exclude=/dev \
    --exclude=/run \
    --exclude=/mnt \
    --exclude=/tmp \
    --exclude=/home \
    --exclude=/var/log \
    / "${BTRFS_TOPVOL}/@/"

log "Syncing /home into @home..."
rsync -axHAX /home/ "${BTRFS_TOPVOL}/@home/" 2>/dev/null || true

log "Syncing /var/log into @var_log..."
rsync -axHAX /var/log/ "${BTRFS_TOPVOL}/@var_log/" 2>/dev/null || true

# ---------------------------------------------------------------------------
# 5. Create necessary mount-point stubs inside @
# ---------------------------------------------------------------------------

mkdir -p \
    "${BTRFS_TOPVOL}/@/home" \
    "${BTRFS_TOPVOL}/@/.snapshots" \
    "${BTRFS_TOPVOL}/@/var/log" \
    "${BTRFS_TOPVOL}/@/tmp" \
    "${BTRFS_TOPVOL}/@/proc" \
    "${BTRFS_TOPVOL}/@/sys" \
    "${BTRFS_TOPVOL}/@/dev" \
    "${BTRFS_TOPVOL}/@/run" \
    "${BTRFS_TOPVOL}/@/mnt"

chmod 1777 "${BTRFS_TOPVOL}/@/tmp"

# ---------------------------------------------------------------------------
# 6. Build the new /etc/fstab inside @
# ---------------------------------------------------------------------------

BTRFS_UUID="$(blkid -s UUID -o value "${ROOT_DEV}")" \
    || die "Cannot read UUID of ${ROOT_DEV}"

# Gather boot & EFI UUIDs (if present)
BOOT_DEV="$(findmnt -n -o SOURCE /boot 2>/dev/null || true)"
BOOT_UUID=""
[[ -n "${BOOT_DEV}" ]] && BOOT_UUID="$(blkid -s UUID -o value "${BOOT_DEV}" 2>/dev/null || true)"

EFI_DEV="$(findmnt -n -o SOURCE /boot/efi 2>/dev/null || true)"
EFI_UUID=""
[[ -n "${EFI_DEV}" ]] && EFI_UUID="$(blkid -s UUID -o value "${EFI_DEV}" 2>/dev/null || true)"

SWAP_DEV="$(swapon --show=NAME --noheadings 2>/dev/null | head -1 || true)"
SWAP_UUID=""
[[ -n "${SWAP_DEV}" ]] && SWAP_UUID="$(blkid -s UUID -o value "${SWAP_DEV}" 2>/dev/null || true)"

log "Writing /etc/fstab (UUID=${BTRFS_UUID})..."

cat > "${BTRFS_TOPVOL}/@/etc/fstab" <<FSTAB
# /etc/fstab – generated by debian-auto-install (btrfs-subvols.sh)
# <file system>  <mount point>  <type>  <options>  <dump>  <pass>

# Btrfs subvolumes
UUID=${BTRFS_UUID}  /            btrfs  ${BTRFS_OPTS},subvol=@            0  0
UUID=${BTRFS_UUID}  /home        btrfs  ${BTRFS_OPTS},subvol=@home        0  0
UUID=${BTRFS_UUID}  /.snapshots  btrfs  ${BTRFS_OPTS},subvol=@snapshots   0  0
UUID=${BTRFS_UUID}  /var/log     btrfs  ${BTRFS_OPTS},subvol=@var_log     0  0
FSTAB

# Append /boot
if [[ -n "${BOOT_UUID}" ]]; then
    echo "UUID=${BOOT_UUID}  /boot      ext4   defaults  0  2" \
        >> "${BTRFS_TOPVOL}/@/etc/fstab"
fi

# Append /boot/efi
if [[ -n "${EFI_UUID}" ]]; then
    echo "UUID=${EFI_UUID}  /boot/efi  vfat   umask=0077  0  1" \
        >> "${BTRFS_TOPVOL}/@/etc/fstab"
fi

# Append swap
if [[ -n "${SWAP_UUID}" ]]; then
    echo "UUID=${SWAP_UUID}  none       swap   sw          0  0" \
        >> "${BTRFS_TOPVOL}/@/etc/fstab"
fi

log "New /etc/fstab:"
cat "${BTRFS_TOPVOL}/@/etc/fstab"

# ---------------------------------------------------------------------------
# 7. Set @ as the Btrfs default subvolume (helps bootloaders)
# ---------------------------------------------------------------------------

SUBVOL_ID="$(btrfs subvolume list "${BTRFS_TOPVOL}" \
    | awk '$NF == "@" {print $2}')"

if [[ -n "${SUBVOL_ID}" ]]; then
    btrfs subvolume set-default "${SUBVOL_ID}" "${BTRFS_TOPVOL}"
    log "Set default subvolume to @ (ID ${SUBVOL_ID})"
else
    log "WARNING: Could not determine ID of @ – default subvolume not changed"
fi

# ---------------------------------------------------------------------------
# 8. Add rootflags=subvol=@ to GRUB kernel command line
# ---------------------------------------------------------------------------

GRUB_DEFAULT="${BTRFS_TOPVOL}/@/etc/default/grub"

if [[ -f "${GRUB_DEFAULT}" ]]; then
    # Inject rootflags only if not already present
    if ! grep -q "rootflags=subvol=@" "${GRUB_DEFAULT}"; then
        sed -i \
            's|^\(GRUB_CMDLINE_LINUX_DEFAULT="\)\(.*\)\(".*\)|\1\2 rootflags=subvol=@\3|' \
            "${GRUB_DEFAULT}"
        log "Injected rootflags=subvol=@ into GRUB_CMDLINE_LINUX_DEFAULT"
    fi
fi

# ---------------------------------------------------------------------------
# 9. Unmount and clean up
# ---------------------------------------------------------------------------

umount "${BTRFS_TOPVOL}"
rmdir  "${BTRFS_TOPVOL}"

log "Btrfs subvolume setup complete."
